version: 2.1
orbs:
  cypress: cypress-io/cypress@1.27.0
workflows:
  build:
    jobs:
      - cypress/run:
          install-command: yarn install --frozen-lockfile
          verify-command: npx cypress verify
          browser: chrome
          spec: cypress/integration/AutoStoreTest*